# Generated by Django 4.0.3 on 2022-04-06 08:45

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.CharField(max_length=30)),
                ('technologies', models.CharField(max_length=500)),
                ('github_link', models.URLField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('liked', models.ManyToManyField(blank=True, null=True, related_name='liked', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='track.track')),
            ],
        ),
    ]
